### PR TITLE
Add CI for the CI scripts

### PR DESCRIPTION
**Pull request by rastersize**
Meta! Basically lints all of our shell scripts using [shellcheck](https://github.com/koalaman/shellcheck).

This will probably show quite a few issues which I intend to resolve in subsequent commits to this PR.

### CODE REVIEW

**Comment by 8W9aG** [comment]
CInception

**Comment by rastersize** [comment]
@8W9aG :joy:

**Comment by rastersize** [comment]
I’ve now tested this with `SPTDataLoader` some minor Travis-CI config changes are needed when bumping.

@8W9aG

**Comment by 8W9aG** [comment]
:+1:

**Pull request merged**
