### PR TITLE
Make sure we define a clang module by default

### PR DESCRIPTION
**Pull request by rastersize**
We want to define a clang module by default for all of our projects. As well as enabling the extra debugging information.

**From the documentation on `CLANG_ENABLE_MODULE_DEBUGGING`:**
> “When this setting is enabled, clang will use the shared debug info available in clang modules and precompiled headers. Results in smaller build artifacts, faster compile times, and more complete debug info. This should only be disabled when building static libraries with debug info for distribution.”

@spotify/objc-dev

### CODE REVIEW

**Review by 8W9aG — APPROVED** [review]
👍

**Comment by dflems** [comment]
@rastersize: Maybe something like:

```
CLANG_ENABLE_MODULE_DEBUGGING_Debug = YES
CLANG_ENABLE_MODULE_DEBUGGING_Release = NO
CLANG_ENABLE_MODULE_DEBUGGING = $(CLANG_ENABLE_MODULE_DEBUGGING_$(CONFIGURATION))
```

**Comment by rastersize** [comment]
@dflems Good suggestion, I’ve updated the PR.

**Review by dflems — APPROVED** [review]
:+1:

**Pull request merged**
